/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    id: BytesLike;
    edPubKeyHash: BytesLike;
    xPubKeyHash: BytesLike;
    owner: AddressLike;
    metadataURI: string;
    registered: BigNumberish;
    lastKeyRotation: BigNumberish;
    active: boolean;
    reputation: BigNumberish;
    stake: BigNumberish;
  };

  export type AgentStructOutput = [
    id: string,
    edPubKeyHash: string,
    xPubKeyHash: string,
    owner: string,
    metadataURI: string,
    registered: bigint,
    lastKeyRotation: bigint,
    active: boolean,
    reputation: bigint,
    stake: bigint
  ] & {
    id: string;
    edPubKeyHash: string;
    xPubKeyHash: string;
    owner: string;
    metadataURI: string;
    registered: bigint;
    lastKeyRotation: bigint;
    active: boolean;
    reputation: bigint;
    stake: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "deactivateAgent"
      | "getAgent"
      | "getAgentByPubKey"
      | "keyRotationCooldown"
      | "minStake"
      | "owner"
      | "ownerAgents"
      | "pubKeyToAgent"
      | "registerAgent"
      | "renounceOwnership"
      | "rotateKeys"
      | "slash"
      | "totalAgents"
      | "transferOwnership"
      | "updateReputation"
      | "verifyAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentRegistered"
      | "AgentSlashed"
      | "KeysRotated"
      | "OwnershipTransferred"
      | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getAgent", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAgentByPubKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "keyRotationCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "minStake", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerAgents",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pubKeyToAgent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rotateKeys",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slash",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAgent",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByPubKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "keyRotationCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pubKeyToAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rotateKeys", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agentId: BytesLike];
  export type OutputTuple = [agentId: string];
  export interface OutputObject {
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BytesLike,
    owner: AddressLike,
    edPubKeyHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: string,
    owner: string,
    edPubKeyHash: string
  ];
  export interface OutputObject {
    agentId: string;
    owner: string;
    edPubKeyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentSlashedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [agentId: string, amount: bigint, reason: string];
  export interface OutputObject {
    agentId: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeysRotatedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    newEdPubKeyHash: BytesLike,
    newXPubKeyHash: BytesLike
  ];
  export type OutputTuple = [
    agentId: string,
    newEdPubKeyHash: string,
    newXPubKeyHash: string
  ];
  export interface OutputObject {
    agentId: string;
    newEdPubKeyHash: string;
    newXPubKeyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [agentId: BytesLike, newReputation: BigNumberish];
  export type OutputTuple = [agentId: string, newReputation: bigint];
  export interface OutputObject {
    agentId: string;
    newReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        id: string;
        edPubKeyHash: string;
        xPubKeyHash: string;
        owner: string;
        metadataURI: string;
        registered: bigint;
        lastKeyRotation: bigint;
        active: boolean;
        reputation: bigint;
        stake: bigint;
      }
    ],
    "view"
  >;

  deactivateAgent: TypedContractMethod<
    [agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  getAgent: TypedContractMethod<
    [agentId: BytesLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  getAgentByPubKey: TypedContractMethod<
    [edPubKeyHash: BytesLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;

  keyRotationCooldown: TypedContractMethod<[], [bigint], "view">;

  minStake: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerAgents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  pubKeyToAgent: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  registerAgent: TypedContractMethod<
    [edPubKeyHash: BytesLike, xPubKeyHash: BytesLike, metadataURI: string],
    [string],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rotateKeys: TypedContractMethod<
    [agentId: BytesLike, newEdPubKeyHash: BytesLike, newXPubKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;

  slash: TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [agentId: BytesLike, delta: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyAgent: TypedContractMethod<
    [agentId: BytesLike, edPubKeyHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        id: string;
        edPubKeyHash: string;
        xPubKeyHash: string;
        owner: string;
        metadataURI: string;
        registered: bigint;
        lastKeyRotation: bigint;
        active: boolean;
        reputation: bigint;
        stake: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentByPubKey"
  ): TypedContractMethod<
    [edPubKeyHash: BytesLike],
    [AgentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "keyRotationCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerAgents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pubKeyToAgent"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [edPubKeyHash: BytesLike, xPubKeyHash: BytesLike, metadataURI: string],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rotateKeys"
  ): TypedContractMethod<
    [agentId: BytesLike, newEdPubKeyHash: BytesLike, newXPubKeyHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slash"
  ): TypedContractMethod<
    [agentId: BytesLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [agentId: BytesLike, delta: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAgent"
  ): TypedContractMethod<
    [agentId: BytesLike, edPubKeyHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentSlashed"
  ): TypedContractEvent<
    AgentSlashedEvent.InputTuple,
    AgentSlashedEvent.OutputTuple,
    AgentSlashedEvent.OutputObject
  >;
  getEvent(
    key: "KeysRotated"
  ): TypedContractEvent<
    KeysRotatedEvent.InputTuple,
    KeysRotatedEvent.OutputTuple,
    KeysRotatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(bytes32)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(bytes32,address,bytes32)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentSlashed(bytes32,uint256,string)": TypedContractEvent<
      AgentSlashedEvent.InputTuple,
      AgentSlashedEvent.OutputTuple,
      AgentSlashedEvent.OutputObject
    >;
    AgentSlashed: TypedContractEvent<
      AgentSlashedEvent.InputTuple,
      AgentSlashedEvent.OutputTuple,
      AgentSlashedEvent.OutputObject
    >;

    "KeysRotated(bytes32,bytes32,bytes32)": TypedContractEvent<
      KeysRotatedEvent.InputTuple,
      KeysRotatedEvent.OutputTuple,
      KeysRotatedEvent.OutputObject
    >;
    KeysRotated: TypedContractEvent<
      KeysRotatedEvent.InputTuple,
      KeysRotatedEvent.OutputTuple,
      KeysRotatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationUpdated(bytes32,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
