/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DACRegistry {
  export type DACStruct = {
    id: BytesLike;
    owner: AddressLike;
    metadataURI: string;
    created: BigNumberish;
    updated: BigNumberish;
    active: boolean;
    stake: BigNumberish;
  };

  export type DACStructOutput = [
    id: string,
    owner: string,
    metadataURI: string,
    created: bigint,
    updated: bigint,
    active: boolean,
    stake: bigint
  ] & {
    id: string;
    owner: string;
    metadataURI: string;
    created: bigint;
    updated: bigint;
    active: boolean;
    stake: bigint;
  };
}

export interface DACRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addStake"
      | "dacPermissions"
      | "dacs"
      | "deactivateDAC"
      | "getDAC"
      | "getOwnerDACs"
      | "grantPermission"
      | "hasPermission"
      | "minStake"
      | "owner"
      | "ownerDACs"
      | "registerDAC"
      | "renounceOwnership"
      | "setMinStake"
      | "totalDACs"
      | "transferDAC"
      | "transferOwnership"
      | "updateDAC"
      | "withdrawStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DACDeactivated"
      | "DACRegistered"
      | "DACTransferred"
      | "DACUpdated"
      | "OwnershipTransferred"
      | "PermissionGranted"
      | "PermissionRevoked"
      | "StakeUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "addStake", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "dacPermissions",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dacs", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "deactivateDAC",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getDAC", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getOwnerDACs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantPermission",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPermission",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "minStake", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerDACs",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registerDAC", values: [string]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "totalDACs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferDAC",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDAC",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dacPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dacs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateDAC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDAC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerDACs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerDACs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDAC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalDACs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferDAC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateDAC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
}

export namespace DACDeactivatedEvent {
  export type InputTuple = [dacId: BytesLike];
  export type OutputTuple = [dacId: string];
  export interface OutputObject {
    dacId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DACRegisteredEvent {
  export type InputTuple = [
    dacId: BytesLike,
    owner: AddressLike,
    metadataURI: string
  ];
  export type OutputTuple = [dacId: string, owner: string, metadataURI: string];
  export interface OutputObject {
    dacId: string;
    owner: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DACTransferredEvent {
  export type InputTuple = [
    dacId: BytesLike,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [dacId: string, from: string, to: string];
  export interface OutputObject {
    dacId: string;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DACUpdatedEvent {
  export type InputTuple = [dacId: BytesLike, metadataURI: string];
  export type OutputTuple = [dacId: string, metadataURI: string];
  export interface OutputObject {
    dacId: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermissionGrantedEvent {
  export type InputTuple = [
    dacId: BytesLike,
    account: AddressLike,
    role: BigNumberish
  ];
  export type OutputTuple = [dacId: string, account: string, role: bigint];
  export interface OutputObject {
    dacId: string;
    account: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermissionRevokedEvent {
  export type InputTuple = [dacId: BytesLike, account: AddressLike];
  export type OutputTuple = [dacId: string, account: string];
  export interface OutputObject {
    dacId: string;
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeUpdatedEvent {
  export type InputTuple = [dacId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [dacId: string, amount: bigint];
  export interface OutputObject {
    dacId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DACRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DACRegistry;
  waitForDeployment(): Promise<this>;

  interface: DACRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addStake: TypedContractMethod<[dacId: BytesLike], [void], "payable">;

  dacPermissions: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        account: string;
        role: bigint;
        expiry: bigint;
      }
    ],
    "view"
  >;

  dacs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, bigint] & {
        id: string;
        owner: string;
        metadataURI: string;
        created: bigint;
        updated: bigint;
        active: boolean;
        stake: bigint;
      }
    ],
    "view"
  >;

  deactivateDAC: TypedContractMethod<[dacId: BytesLike], [void], "nonpayable">;

  getDAC: TypedContractMethod<
    [dacId: BytesLike],
    [DACRegistry.DACStructOutput],
    "view"
  >;

  getOwnerDACs: TypedContractMethod<[owner: AddressLike], [string[]], "view">;

  grantPermission: TypedContractMethod<
    [
      dacId: BytesLike,
      account: AddressLike,
      role: BigNumberish,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  hasPermission: TypedContractMethod<
    [dacId: BytesLike, account: AddressLike, minRole: BigNumberish],
    [boolean],
    "view"
  >;

  minStake: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerDACs: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  registerDAC: TypedContractMethod<[metadataURI: string], [string], "payable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMinStake: TypedContractMethod<
    [_minStake: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalDACs: TypedContractMethod<[], [bigint], "view">;

  transferDAC: TypedContractMethod<
    [dacId: BytesLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateDAC: TypedContractMethod<
    [dacId: BytesLike, metadataURI: string],
    [void],
    "nonpayable"
  >;

  withdrawStake: TypedContractMethod<
    [dacId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addStake"
  ): TypedContractMethod<[dacId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "dacPermissions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        account: string;
        role: bigint;
        expiry: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "dacs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean, bigint] & {
        id: string;
        owner: string;
        metadataURI: string;
        created: bigint;
        updated: bigint;
        active: boolean;
        stake: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateDAC"
  ): TypedContractMethod<[dacId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDAC"
  ): TypedContractMethod<
    [dacId: BytesLike],
    [DACRegistry.DACStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerDACs"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantPermission"
  ): TypedContractMethod<
    [
      dacId: BytesLike,
      account: AddressLike,
      role: BigNumberish,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasPermission"
  ): TypedContractMethod<
    [dacId: BytesLike, account: AddressLike, minRole: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "minStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerDACs"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerDAC"
  ): TypedContractMethod<[metadataURI: string], [string], "payable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinStake"
  ): TypedContractMethod<[_minStake: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalDACs"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferDAC"
  ): TypedContractMethod<
    [dacId: BytesLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDAC"
  ): TypedContractMethod<
    [dacId: BytesLike, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<
    [dacId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DACDeactivated"
  ): TypedContractEvent<
    DACDeactivatedEvent.InputTuple,
    DACDeactivatedEvent.OutputTuple,
    DACDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "DACRegistered"
  ): TypedContractEvent<
    DACRegisteredEvent.InputTuple,
    DACRegisteredEvent.OutputTuple,
    DACRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DACTransferred"
  ): TypedContractEvent<
    DACTransferredEvent.InputTuple,
    DACTransferredEvent.OutputTuple,
    DACTransferredEvent.OutputObject
  >;
  getEvent(
    key: "DACUpdated"
  ): TypedContractEvent<
    DACUpdatedEvent.InputTuple,
    DACUpdatedEvent.OutputTuple,
    DACUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PermissionGranted"
  ): TypedContractEvent<
    PermissionGrantedEvent.InputTuple,
    PermissionGrantedEvent.OutputTuple,
    PermissionGrantedEvent.OutputObject
  >;
  getEvent(
    key: "PermissionRevoked"
  ): TypedContractEvent<
    PermissionRevokedEvent.InputTuple,
    PermissionRevokedEvent.OutputTuple,
    PermissionRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StakeUpdated"
  ): TypedContractEvent<
    StakeUpdatedEvent.InputTuple,
    StakeUpdatedEvent.OutputTuple,
    StakeUpdatedEvent.OutputObject
  >;

  filters: {
    "DACDeactivated(bytes32)": TypedContractEvent<
      DACDeactivatedEvent.InputTuple,
      DACDeactivatedEvent.OutputTuple,
      DACDeactivatedEvent.OutputObject
    >;
    DACDeactivated: TypedContractEvent<
      DACDeactivatedEvent.InputTuple,
      DACDeactivatedEvent.OutputTuple,
      DACDeactivatedEvent.OutputObject
    >;

    "DACRegistered(bytes32,address,string)": TypedContractEvent<
      DACRegisteredEvent.InputTuple,
      DACRegisteredEvent.OutputTuple,
      DACRegisteredEvent.OutputObject
    >;
    DACRegistered: TypedContractEvent<
      DACRegisteredEvent.InputTuple,
      DACRegisteredEvent.OutputTuple,
      DACRegisteredEvent.OutputObject
    >;

    "DACTransferred(bytes32,address,address)": TypedContractEvent<
      DACTransferredEvent.InputTuple,
      DACTransferredEvent.OutputTuple,
      DACTransferredEvent.OutputObject
    >;
    DACTransferred: TypedContractEvent<
      DACTransferredEvent.InputTuple,
      DACTransferredEvent.OutputTuple,
      DACTransferredEvent.OutputObject
    >;

    "DACUpdated(bytes32,string)": TypedContractEvent<
      DACUpdatedEvent.InputTuple,
      DACUpdatedEvent.OutputTuple,
      DACUpdatedEvent.OutputObject
    >;
    DACUpdated: TypedContractEvent<
      DACUpdatedEvent.InputTuple,
      DACUpdatedEvent.OutputTuple,
      DACUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PermissionGranted(bytes32,address,uint8)": TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;
    PermissionGranted: TypedContractEvent<
      PermissionGrantedEvent.InputTuple,
      PermissionGrantedEvent.OutputTuple,
      PermissionGrantedEvent.OutputObject
    >;

    "PermissionRevoked(bytes32,address)": TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;
    PermissionRevoked: TypedContractEvent<
      PermissionRevokedEvent.InputTuple,
      PermissionRevokedEvent.OutputTuple,
      PermissionRevokedEvent.OutputObject
    >;

    "StakeUpdated(bytes32,uint256)": TypedContractEvent<
      StakeUpdatedEvent.InputTuple,
      StakeUpdatedEvent.OutputTuple,
      StakeUpdatedEvent.OutputObject
    >;
    StakeUpdated: TypedContractEvent<
      StakeUpdatedEvent.InputTuple,
      StakeUpdatedEvent.OutputTuple,
      StakeUpdatedEvent.OutputObject
    >;
  };
}
