/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DataStream {
  export type ChannelStruct = {
    id: BytesLike;
    dacId: BytesLike;
    owner: AddressLike;
    pricePerByte: BigNumberish;
    pricePerMessage: BigNumberish;
    subscriptionFee: BigNumberish;
    created: BigNumberish;
    active: boolean;
    totalRevenue: BigNumberish;
  };

  export type ChannelStructOutput = [
    id: string,
    dacId: string,
    owner: string,
    pricePerByte: bigint,
    pricePerMessage: bigint,
    subscriptionFee: bigint,
    created: bigint,
    active: boolean,
    totalRevenue: bigint
  ] & {
    id: string;
    dacId: string;
    owner: string;
    pricePerByte: bigint;
    pricePerMessage: bigint;
    subscriptionFee: bigint;
    created: bigint;
    active: boolean;
    totalRevenue: bigint;
  };

  export type SubscriptionStruct = {
    since: BigNumberish;
    deposited: BigNumberish;
    used: BigNumberish;
    bytesConsumed: BigNumberish;
    messagesConsumed: BigNumberish;
    active: boolean;
  };

  export type SubscriptionStructOutput = [
    since: bigint,
    deposited: bigint,
    used: bigint,
    bytesConsumed: bigint,
    messagesConsumed: bigint,
    active: boolean
  ] & {
    since: bigint;
    deposited: bigint;
    used: bigint;
    bytesConsumed: bigint;
    messagesConsumed: bigint;
    active: boolean;
  };
}

export interface DataStreamInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "channelSubscribers"
      | "channels"
      | "closeChannel"
      | "createChannel"
      | "dacChannels"
      | "getChannel"
      | "getDACChannels"
      | "getSubscription"
      | "owner"
      | "platformFeePercent"
      | "recordUsage"
      | "renounceOwnership"
      | "settle"
      | "subscribe"
      | "subscriptions"
      | "topUp"
      | "totalChannels"
      | "transferOwnership"
      | "updateChannel"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChannelClosed"
      | "ChannelCreated"
      | "ChannelUpdated"
      | "OwnershipTransferred"
      | "Settled"
      | "Subscribed"
      | "Unsubscribed"
      | "UsageRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "channelSubscribers",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "channels", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "closeChannel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createChannel",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dacChannels",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChannel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDACChannels",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordUsage",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "settle", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "topUp", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "totalChannels",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateChannel",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "channelSubscribers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "channels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dacChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChannel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDACChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "topUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateChannel",
    data: BytesLike
  ): Result;
}

export namespace ChannelClosedEvent {
  export type InputTuple = [channelId: BytesLike];
  export type OutputTuple = [channelId: string];
  export interface OutputObject {
    channelId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelCreatedEvent {
  export type InputTuple = [
    channelId: BytesLike,
    dacId: BytesLike,
    owner: AddressLike
  ];
  export type OutputTuple = [channelId: string, dacId: string, owner: string];
  export interface OutputObject {
    channelId: string;
    dacId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelUpdatedEvent {
  export type InputTuple = [channelId: BytesLike];
  export type OutputTuple = [channelId: string];
  export interface OutputObject {
    channelId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettledEvent {
  export type InputTuple = [channelId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [channelId: string, amount: bigint];
  export interface OutputObject {
    channelId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    channelId: BytesLike,
    subscriber: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    channelId: string,
    subscriber: string,
    amount: bigint
  ];
  export interface OutputObject {
    channelId: string;
    subscriber: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnsubscribedEvent {
  export type InputTuple = [channelId: BytesLike, subscriber: AddressLike];
  export type OutputTuple = [channelId: string, subscriber: string];
  export interface OutputObject {
    channelId: string;
    subscriber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsageRecordedEvent {
  export type InputTuple = [
    channelId: BytesLike,
    user: AddressLike,
    bytes_: BigNumberish,
    messages: BigNumberish
  ];
  export type OutputTuple = [
    channelId: string,
    user: string,
    bytes_: bigint,
    messages: bigint
  ];
  export interface OutputObject {
    channelId: string;
    user: string;
    bytes_: bigint;
    messages: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataStream extends BaseContract {
  connect(runner?: ContractRunner | null): DataStream;
  waitForDeployment(): Promise<this>;

  interface: DataStreamInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  channelSubscribers: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  channels: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: string;
        dacId: string;
        owner: string;
        pricePerByte: bigint;
        pricePerMessage: bigint;
        subscriptionFee: bigint;
        created: bigint;
        active: boolean;
        totalRevenue: bigint;
      }
    ],
    "view"
  >;

  closeChannel: TypedContractMethod<
    [channelId: BytesLike],
    [void],
    "nonpayable"
  >;

  createChannel: TypedContractMethod<
    [
      dacId: BytesLike,
      pricePerByte: BigNumberish,
      pricePerMessage: BigNumberish,
      subscriptionFee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  dacChannels: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getChannel: TypedContractMethod<
    [channelId: BytesLike],
    [DataStream.ChannelStructOutput],
    "view"
  >;

  getDACChannels: TypedContractMethod<[dacId: BytesLike], [string[]], "view">;

  getSubscription: TypedContractMethod<
    [channelId: BytesLike, user: AddressLike],
    [DataStream.SubscriptionStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  recordUsage: TypedContractMethod<
    [
      channelId: BytesLike,
      user: AddressLike,
      bytes_: BigNumberish,
      messages: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settle: TypedContractMethod<[channelId: BytesLike], [bigint], "nonpayable">;

  subscribe: TypedContractMethod<[channelId: BytesLike], [void], "payable">;

  subscriptions: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        since: bigint;
        deposited: bigint;
        used: bigint;
        bytesConsumed: bigint;
        messagesConsumed: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  topUp: TypedContractMethod<[channelId: BytesLike], [void], "payable">;

  totalChannels: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateChannel: TypedContractMethod<
    [
      channelId: BytesLike,
      pricePerByte: BigNumberish,
      pricePerMessage: BigNumberish,
      subscriptionFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "channelSubscribers"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "channels"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: string;
        dacId: string;
        owner: string;
        pricePerByte: bigint;
        pricePerMessage: bigint;
        subscriptionFee: bigint;
        created: bigint;
        active: boolean;
        totalRevenue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeChannel"
  ): TypedContractMethod<[channelId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createChannel"
  ): TypedContractMethod<
    [
      dacId: BytesLike,
      pricePerByte: BigNumberish,
      pricePerMessage: BigNumberish,
      subscriptionFee: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dacChannels"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChannel"
  ): TypedContractMethod<
    [channelId: BytesLike],
    [DataStream.ChannelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDACChannels"
  ): TypedContractMethod<[dacId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [channelId: BytesLike, user: AddressLike],
    [DataStream.SubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordUsage"
  ): TypedContractMethod<
    [
      channelId: BytesLike,
      user: AddressLike,
      bytes_: BigNumberish,
      messages: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[channelId: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[channelId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        since: bigint;
        deposited: bigint;
        used: bigint;
        bytesConsumed: bigint;
        messagesConsumed: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "topUp"
  ): TypedContractMethod<[channelId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "totalChannels"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateChannel"
  ): TypedContractMethod<
    [
      channelId: BytesLike,
      pricePerByte: BigNumberish,
      pricePerMessage: BigNumberish,
      subscriptionFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ChannelClosed"
  ): TypedContractEvent<
    ChannelClosedEvent.InputTuple,
    ChannelClosedEvent.OutputTuple,
    ChannelClosedEvent.OutputObject
  >;
  getEvent(
    key: "ChannelCreated"
  ): TypedContractEvent<
    ChannelCreatedEvent.InputTuple,
    ChannelCreatedEvent.OutputTuple,
    ChannelCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ChannelUpdated"
  ): TypedContractEvent<
    ChannelUpdatedEvent.InputTuple,
    ChannelUpdatedEvent.OutputTuple,
    ChannelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Settled"
  ): TypedContractEvent<
    SettledEvent.InputTuple,
    SettledEvent.OutputTuple,
    SettledEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "Unsubscribed"
  ): TypedContractEvent<
    UnsubscribedEvent.InputTuple,
    UnsubscribedEvent.OutputTuple,
    UnsubscribedEvent.OutputObject
  >;
  getEvent(
    key: "UsageRecorded"
  ): TypedContractEvent<
    UsageRecordedEvent.InputTuple,
    UsageRecordedEvent.OutputTuple,
    UsageRecordedEvent.OutputObject
  >;

  filters: {
    "ChannelClosed(bytes32)": TypedContractEvent<
      ChannelClosedEvent.InputTuple,
      ChannelClosedEvent.OutputTuple,
      ChannelClosedEvent.OutputObject
    >;
    ChannelClosed: TypedContractEvent<
      ChannelClosedEvent.InputTuple,
      ChannelClosedEvent.OutputTuple,
      ChannelClosedEvent.OutputObject
    >;

    "ChannelCreated(bytes32,bytes32,address)": TypedContractEvent<
      ChannelCreatedEvent.InputTuple,
      ChannelCreatedEvent.OutputTuple,
      ChannelCreatedEvent.OutputObject
    >;
    ChannelCreated: TypedContractEvent<
      ChannelCreatedEvent.InputTuple,
      ChannelCreatedEvent.OutputTuple,
      ChannelCreatedEvent.OutputObject
    >;

    "ChannelUpdated(bytes32)": TypedContractEvent<
      ChannelUpdatedEvent.InputTuple,
      ChannelUpdatedEvent.OutputTuple,
      ChannelUpdatedEvent.OutputObject
    >;
    ChannelUpdated: TypedContractEvent<
      ChannelUpdatedEvent.InputTuple,
      ChannelUpdatedEvent.OutputTuple,
      ChannelUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Settled(bytes32,uint256)": TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;
    Settled: TypedContractEvent<
      SettledEvent.InputTuple,
      SettledEvent.OutputTuple,
      SettledEvent.OutputObject
    >;

    "Subscribed(bytes32,address,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "Unsubscribed(bytes32,address)": TypedContractEvent<
      UnsubscribedEvent.InputTuple,
      UnsubscribedEvent.OutputTuple,
      UnsubscribedEvent.OutputObject
    >;
    Unsubscribed: TypedContractEvent<
      UnsubscribedEvent.InputTuple,
      UnsubscribedEvent.OutputTuple,
      UnsubscribedEvent.OutputObject
    >;

    "UsageRecorded(bytes32,address,uint256,uint256)": TypedContractEvent<
      UsageRecordedEvent.InputTuple,
      UsageRecordedEvent.OutputTuple,
      UsageRecordedEvent.OutputObject
    >;
    UsageRecorded: TypedContractEvent<
      UsageRecordedEvent.InputTuple,
      UsageRecordedEvent.OutputTuple,
      UsageRecordedEvent.OutputObject
    >;
  };
}
