/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MsgEscrow {
  export type LockStruct = {
    id: BytesLike;
    payer: AddressLike;
    payee: AddressLike;
    amount: BigNumberish;
    messageHash: BytesLike;
    created: BigNumberish;
    expiry: BigNumberish;
    released: boolean;
    cancelled: boolean;
  };

  export type LockStructOutput = [
    id: string,
    payer: string,
    payee: string,
    amount: bigint,
    messageHash: string,
    created: bigint,
    expiry: bigint,
    released: boolean,
    cancelled: boolean
  ] & {
    id: string;
    payer: string;
    payee: string;
    amount: bigint;
    messageHash: string;
    created: bigint;
    expiry: bigint;
    released: boolean;
    cancelled: boolean;
  };
}

export interface MsgEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRelayer"
      | "authorizedRelayers"
      | "cancel"
      | "defaultExpiry"
      | "getLock"
      | "lock"
      | "locks"
      | "minLockAmount"
      | "owner"
      | "paymentToken"
      | "relayerBondAmount"
      | "relayerBonds"
      | "release"
      | "removeRelayer"
      | "renounceOwnership"
      | "setDefaultExpiry"
      | "setMinLockAmount"
      | "setRelayerBondAmount"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Cancelled"
      | "Locked"
      | "OwnershipTransferred"
      | "RelayerAdded"
      | "RelayerRemoved"
      | "Released"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedRelayers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "cancel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "defaultExpiry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getLock", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "lock",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "locks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "minLockAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relayerBondAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relayerBonds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "release", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "removeRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultExpiry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinLockAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayerBondAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedRelayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minLockAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayerBondAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayerBonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinLockAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRelayerBondAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CancelledEvent {
  export type InputTuple = [lockId: BytesLike];
  export type OutputTuple = [lockId: string];
  export interface OutputObject {
    lockId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockedEvent {
  export type InputTuple = [
    lockId: BytesLike,
    payer: AddressLike,
    payee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    lockId: string,
    payer: string,
    payee: string,
    amount: bigint
  ];
  export interface OutputObject {
    lockId: string;
    payer: string;
    payee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerAddedEvent {
  export type InputTuple = [relayer: AddressLike];
  export type OutputTuple = [relayer: string];
  export interface OutputObject {
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerRemovedEvent {
  export type InputTuple = [relayer: AddressLike];
  export type OutputTuple = [relayer: string];
  export interface OutputObject {
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [lockId: BytesLike, relayer: AddressLike];
  export type OutputTuple = [lockId: string, relayer: string];
  export interface OutputObject {
    lockId: string;
    relayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MsgEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): MsgEscrow;
  waitForDeployment(): Promise<this>;

  interface: MsgEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRelayer: TypedContractMethod<[], [void], "payable">;

  authorizedRelayers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  cancel: TypedContractMethod<[lockId: BytesLike], [boolean], "nonpayable">;

  defaultExpiry: TypedContractMethod<[], [bigint], "view">;

  getLock: TypedContractMethod<
    [lockId: BytesLike],
    [MsgEscrow.LockStructOutput],
    "view"
  >;

  lock: TypedContractMethod<
    [
      lockId: BytesLike,
      payee: AddressLike,
      amount: BigNumberish,
      messageHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  locks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: string;
        payer: string;
        payee: string;
        amount: bigint;
        messageHash: string;
        created: bigint;
        expiry: bigint;
        released: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  minLockAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  relayerBondAmount: TypedContractMethod<[], [bigint], "view">;

  relayerBonds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  release: TypedContractMethod<[lockId: BytesLike], [boolean], "nonpayable">;

  removeRelayer: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDefaultExpiry: TypedContractMethod<
    [_expiry: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinLockAmount: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRelayerBondAmount: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRelayer"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "authorizedRelayers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[lockId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultExpiry"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLock"
  ): TypedContractMethod<
    [lockId: BytesLike],
    [MsgEscrow.LockStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lock"
  ): TypedContractMethod<
    [
      lockId: BytesLike,
      payee: AddressLike,
      amount: BigNumberish,
      messageHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "locks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: string;
        payer: string;
        payee: string;
        amount: bigint;
        messageHash: string;
        created: bigint;
        expiry: bigint;
        released: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "minLockAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayerBondAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "relayerBonds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[lockId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "removeRelayer"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultExpiry"
  ): TypedContractMethod<[_expiry: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinLockAmount"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRelayerBondAmount"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Cancelled"
  ): TypedContractEvent<
    CancelledEvent.InputTuple,
    CancelledEvent.OutputTuple,
    CancelledEvent.OutputObject
  >;
  getEvent(
    key: "Locked"
  ): TypedContractEvent<
    LockedEvent.InputTuple,
    LockedEvent.OutputTuple,
    LockedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RelayerAdded"
  ): TypedContractEvent<
    RelayerAddedEvent.InputTuple,
    RelayerAddedEvent.OutputTuple,
    RelayerAddedEvent.OutputObject
  >;
  getEvent(
    key: "RelayerRemoved"
  ): TypedContractEvent<
    RelayerRemovedEvent.InputTuple,
    RelayerRemovedEvent.OutputTuple,
    RelayerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;

  filters: {
    "Cancelled(bytes32)": TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;
    Cancelled: TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;

    "Locked(bytes32,address,address,uint256)": TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;
    Locked: TypedContractEvent<
      LockedEvent.InputTuple,
      LockedEvent.OutputTuple,
      LockedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RelayerAdded(address)": TypedContractEvent<
      RelayerAddedEvent.InputTuple,
      RelayerAddedEvent.OutputTuple,
      RelayerAddedEvent.OutputObject
    >;
    RelayerAdded: TypedContractEvent<
      RelayerAddedEvent.InputTuple,
      RelayerAddedEvent.OutputTuple,
      RelayerAddedEvent.OutputObject
    >;

    "RelayerRemoved(address)": TypedContractEvent<
      RelayerRemovedEvent.InputTuple,
      RelayerRemovedEvent.OutputTuple,
      RelayerRemovedEvent.OutputObject
    >;
    RelayerRemoved: TypedContractEvent<
      RelayerRemovedEvent.InputTuple,
      RelayerRemovedEvent.OutputTuple,
      RelayerRemovedEvent.OutputObject
    >;

    "Released(bytes32,address)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
  };
}
