/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentRegistry {
  export type AgentStruct = {
    id: BytesLike;
    edPubKeyHash: BytesLike;
    xPubKeyHash: BytesLike;
    owner: AddressLike;
    metadataURI: string;
    registered: BigNumberish;
    lastKeyRotation: BigNumberish;
    active: boolean;
    reputation: BigNumberish;
    stake: BigNumberish;
  };

  export type AgentStructOutput = [
    id: string,
    edPubKeyHash: string,
    xPubKeyHash: string,
    owner: string,
    metadataURI: string,
    registered: bigint,
    lastKeyRotation: bigint,
    active: boolean,
    reputation: bigint,
    stake: bigint
  ] & {
    id: string;
    edPubKeyHash: string;
    xPubKeyHash: string;
    owner: string;
    metadataURI: string;
    registered: bigint;
    lastKeyRotation: bigint;
    active: boolean;
    reputation: bigint;
    stake: bigint;
  };
}

export declare namespace DACRegistry {
  export type DACStruct = {
    id: BytesLike;
    owner: AddressLike;
    metadataURI: string;
    created: BigNumberish;
    updated: BigNumberish;
    active: boolean;
    stake: BigNumberish;
  };

  export type DACStructOutput = [
    id: string,
    owner: string,
    metadataURI: string,
    created: bigint,
    updated: bigint,
    active: boolean,
    stake: bigint
  ] & {
    id: string;
    owner: string;
    metadataURI: string;
    created: bigint;
    updated: bigint;
    active: boolean;
    stake: bigint;
  };
}

export interface OpacusCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentDAC"
      | "agentRegistry"
      | "assignAgentToDAC"
      | "dacAgents"
      | "dacRegistry"
      | "dataStream"
      | "escrow"
      | "getAgentDAC"
      | "getDACAgents"
      | "getFullAgentInfo"
      | "initialize"
      | "owner"
      | "removeAgentFromDAC"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAssignedToDAC"
      | "AgentRemovedFromDAC"
      | "ContractsInitialized"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agentDAC", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assignAgentToDAC",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dacAgents",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dacRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataStream",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAgentDAC",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDACAgents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFullAgentInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAgentFromDAC",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "agentDAC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignAgentToDAC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dacAgents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dacRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dataStream", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentDAC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDACAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFullAgentInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAgentFromDAC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentAssignedToDACEvent {
  export type InputTuple = [agentId: BytesLike, dacId: BytesLike];
  export type OutputTuple = [agentId: string, dacId: string];
  export interface OutputObject {
    agentId: string;
    dacId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRemovedFromDACEvent {
  export type InputTuple = [agentId: BytesLike, dacId: BytesLike];
  export type OutputTuple = [agentId: string, dacId: string];
  export interface OutputObject {
    agentId: string;
    dacId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractsInitializedEvent {
  export type InputTuple = [
    dacRegistry: AddressLike,
    agentRegistry: AddressLike,
    dataStream: AddressLike,
    escrow: AddressLike
  ];
  export type OutputTuple = [
    dacRegistry: string,
    agentRegistry: string,
    dataStream: string,
    escrow: string
  ];
  export interface OutputObject {
    dacRegistry: string;
    agentRegistry: string;
    dataStream: string;
    escrow: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OpacusCore extends BaseContract {
  connect(runner?: ContractRunner | null): OpacusCore;
  waitForDeployment(): Promise<this>;

  interface: OpacusCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentDAC: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  assignAgentToDAC: TypedContractMethod<
    [agentId: BytesLike, dacId: BytesLike],
    [void],
    "nonpayable"
  >;

  dacAgents: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  dacRegistry: TypedContractMethod<[], [string], "view">;

  dataStream: TypedContractMethod<[], [string], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  getAgentDAC: TypedContractMethod<[agentId: BytesLike], [string], "view">;

  getDACAgents: TypedContractMethod<[dacId: BytesLike], [string[]], "view">;

  getFullAgentInfo: TypedContractMethod<
    [agentId: BytesLike],
    [
      [AgentRegistry.AgentStructOutput, string, DACRegistry.DACStructOutput] & {
        agent: AgentRegistry.AgentStructOutput;
        dacId: string;
        dac: DACRegistry.DACStructOutput;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _dacRegistry: AddressLike,
      _agentRegistry: AddressLike,
      _dataStream: AddressLike,
      _escrow: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeAgentFromDAC: TypedContractMethod<
    [agentId: BytesLike, dacId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentDAC"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assignAgentToDAC"
  ): TypedContractMethod<
    [agentId: BytesLike, dacId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dacAgents"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "dacRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dataStream"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentDAC"
  ): TypedContractMethod<[agentId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDACAgents"
  ): TypedContractMethod<[dacId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getFullAgentInfo"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [
      [AgentRegistry.AgentStructOutput, string, DACRegistry.DACStructOutput] & {
        agent: AgentRegistry.AgentStructOutput;
        dacId: string;
        dac: DACRegistry.DACStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _dacRegistry: AddressLike,
      _agentRegistry: AddressLike,
      _dataStream: AddressLike,
      _escrow: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAgentFromDAC"
  ): TypedContractMethod<
    [agentId: BytesLike, dacId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentAssignedToDAC"
  ): TypedContractEvent<
    AgentAssignedToDACEvent.InputTuple,
    AgentAssignedToDACEvent.OutputTuple,
    AgentAssignedToDACEvent.OutputObject
  >;
  getEvent(
    key: "AgentRemovedFromDAC"
  ): TypedContractEvent<
    AgentRemovedFromDACEvent.InputTuple,
    AgentRemovedFromDACEvent.OutputTuple,
    AgentRemovedFromDACEvent.OutputObject
  >;
  getEvent(
    key: "ContractsInitialized"
  ): TypedContractEvent<
    ContractsInitializedEvent.InputTuple,
    ContractsInitializedEvent.OutputTuple,
    ContractsInitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgentAssignedToDAC(bytes32,bytes32)": TypedContractEvent<
      AgentAssignedToDACEvent.InputTuple,
      AgentAssignedToDACEvent.OutputTuple,
      AgentAssignedToDACEvent.OutputObject
    >;
    AgentAssignedToDAC: TypedContractEvent<
      AgentAssignedToDACEvent.InputTuple,
      AgentAssignedToDACEvent.OutputTuple,
      AgentAssignedToDACEvent.OutputObject
    >;

    "AgentRemovedFromDAC(bytes32,bytes32)": TypedContractEvent<
      AgentRemovedFromDACEvent.InputTuple,
      AgentRemovedFromDACEvent.OutputTuple,
      AgentRemovedFromDACEvent.OutputObject
    >;
    AgentRemovedFromDAC: TypedContractEvent<
      AgentRemovedFromDACEvent.InputTuple,
      AgentRemovedFromDACEvent.OutputTuple,
      AgentRemovedFromDACEvent.OutputObject
    >;

    "ContractsInitialized(address,address,address,address)": TypedContractEvent<
      ContractsInitializedEvent.InputTuple,
      ContractsInitializedEvent.OutputTuple,
      ContractsInitializedEvent.OutputObject
    >;
    ContractsInitialized: TypedContractEvent<
      ContractsInitializedEvent.InputTuple,
      ContractsInitializedEvent.OutputTuple,
      ContractsInitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
